# hai ffdfdse
version: 2.1

orbs:
  node: circleci/node@4.1
  docker: circleci/docker@1.7.0


jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: haigun81/docker-reacts
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - docker/check:
          docker-password: DOCKER_PASSWORD
          docker-username: DOCKER_USER
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy:
    executor: docker/docker
    steps:
      - add_ssh_keys:
          fingerprints:
            - "18:4a:f5:e4:15:19:4e:d6:86:53:70:c8:2d:f0:f8:89"
      - run:
          name: Login into Heroku Docker Repository
          command: |
            docker login --username=HEROKU_LOGIN --password=HEROKU_API_KEY cicd-hai.herokuapp.com
      - run: 
         heroku container:push  -a cicd-hai.herokuapp.com --arg web 
         heroku container:release  -a << parameters.app-name >>
workflows:
  build-deploy:
    jobs:
      - node/test
      - build-and-push:
          requires:
            - node/test
          filters:
            branches:
              only:
                - main 
      - deploy