# hai ffdfdse
version: 2.1

orbs:
  node: circleci/node@4.1
  docker: circleci/docker@1.7.0


jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: docker-hai
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker:
          version:  20.10.8
      - checkout
      - docker/check:
          docker-password: DOCKER_PASSWORD
          docker-username: DOCKER_USER
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: my_repo/orb-test
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
workflows:
  build-deploy:
    jobs:
      - node/test
      - build-and-push:
          requires:
              - node/test
          filters:
            branches:
              only:
                - main 
